// Product shirts
export const PRODUCT_SHIRTS_LOADING = 'PRODUCT_SHIRTS_LOADING';
export const PRODUCT_SHIRTS_LOADED = 'PRODUCT_SHIRTS_LOADED';
export const PRODUCT_SHIRTS_FAILED = 'PRODUCT_SHIRTS_FAILED';

// Product pants
export const PRODUCT_PANTS_LOADING = 'PRODUCT_PANTS_LOADING';
export const PRODUCT_PANTS_LOADED = 'PRODUCT_PANTS_LOADED';
export const PRODUCT_PANTS_FAILED = 'PRODUCT_PANTS_FAILED';

// Order
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';